### ISSUE TITLE
01_gan-intro_Introduction to GAN 中代码的解释

### ISSUE THREAD

**Issue by Terrynech** [wangx404/GAN_gluon_tutorials#1]
`netD = nn.Sequential()
with netD.name_scope():
    netD.add(nn.Dense(5, activation='tanh'))
    netD.add(nn.Dense(3, activation='tanh'))
    netD.add(nn.Dense(2))`
请问netD的输出为什么是两个?
是不是一个预测样本x来自真实数据的概率,一个预测样本x来自生成器的概率?

**Comment by wangx404** [comment]
因为在这个示例当中要生成的数据是一个二维的数据分布，所以输出层的神经元是两个。

**Comment by tyxsspa** [comment]
这个是判别，不是生成啊，为什么判别网络D的输出是两个呢？改成1个反而效果不好，求解答...
