### ISSUE TITLE
请问第二节中如何提高生产的人脸图片的效果？

### ISSUE THREAD

**Issue by JcYooo** [wangx404/GAN_gluon_tutorials#2]
请问运行原始网络，即使增加了迭代次数，生成的人脸图片效果也很差，请问怎么能提高生成的图片质量呢？

**Comment by wangx404** [comment]
这个你就得去看看最新的论文了。这个教程只是简单地把相关的模型结构展示一下。

**Comment by JcYooo** [comment]
好的，也非常感谢大佬的翻译！
